/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Mega Man Legends)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800123B8u
#define func_800123B8 BootEntry  /* alias */
